name: lint and test sql formatting 
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  lint_and_test_project:
    name: Lint and Test dbt project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install SQLFluff and dbt
        run: |
          pip install dbt-snowflake
          pip install sqlfluff
          pip install sqlfluff-templater-dbt
      - name: Lint project
        run: |
          sqlfluff --version
          cd ./models
          sqlfluff lint -i templating,parsing --dialect snowflake .
      - name: Print success message
        run: echo "The source code observes the best practices!"
