# Comments:
# SQLFluff is an open source, dialect-flexible and configurable SQL linter. Designed with ELT applications in mind,
#  SQLFluff also works with Jinja templating and dbt.
# This ci does not require any secrete or variables
name: Sqlfluff CI pipe run
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]
env:
  DBT_PROJECT_NAME: jaffle_shop
jobs:
    compile:
        name: Build and Compile dbt Project
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo hosting the dbt project
            uses: actions/checkout@main
          - name: Set up Python virtual environment
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'
          - name: install sqlfluff python package
            run: pip install sqlfluff
          - name: install sqlfluff templater for dbt
            run: pip install dbt-snowflake sqlfluff-templater-dbt
          - name: linting sql model files
            run: |
                sqlfluff --version
                cd ./models
                sqlfluff lint  -i templating,parsing --dialect snowflake .